#'@examples
#'"/work_projet/ala/metachick-fugace/Analyses_Ouléye/DESMAN_2023/DESMAN_iterAddPost/DESMAN_erm_F__3_M17808/freq2Desman.txt"|>
#'get_data_from_server()|>
#'read_desman_input_files()->X
read_desman_input_files<-
  function(desman_input_file,
           sep="\\.",
           s_pattern="[[:alnum:]]+_+[[:alnum:]]+",
           a_pattern="[[:alnum:]]+"){
    desman_input_file|>read.csv()|>tidyr::pivot_longer(cols=!c("Position","X"),
                           names_to=c("s","a"),
                           names_pattern = paste0("(",s_pattern,")",sep,"(",a_pattern,")"))|>
      plyr::dlply(~X,
                  function(d){
                    d|>dplyr::rename(v="Position")|>
                    plyr::daply(.drop_i=FALSE,
                                .drop_o=TRUE,
                                .variables=~v+s+a,
                                .fun=function(dd){dd$value})})}
